app_id: "9603342a-0630-4e1c-9fb1-fe97746511ae"
app_secret: "txwlRACN800:~abtZDV08@="
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
